apiVersion: v1
kind: ConfigMap
metadata:
  name: controller-config
  labels:
    app: controller
    app.kubernetes.io/part-of: loadforge
data:
  SERVER_PORT: "8080"
  DB_URL: "jdbc:postgresql://postgres:5432/loadforge"
  DB_USERNAME: "postgres"
  KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
  KAFKA_CONSUMER_GROUP: "test-management-service"
