apiVersion: v1
kind: Service
metadata:
  name: worker
  labels:
    app: worker
    app.kubernetes.io/part-of: loadforge
spec:
  type: ClusterIP
  selector:
    app: worker
  ports:
    - name: http
      port: 8081
      targetPort: 8081
